
version: '3.5'
services:
  dq9-server:
    container_name: dq9-server
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./dlc:/run/dlc
      - ./ip.txt:/run/ip.txt
    ports:
      - "${LOCAL_IP}:80:80/tcp"
      - "${LOCAL_IP}:443:443/tcp"
      - "${LOCAL_IP}:53:53/tcp"
